/**
 * Grafista AI Studio — Real Provider Smoke Check (Phase 2 Step 12)
 *
 * Small, controlled connectivity checks against the REAL providers the MVP
 * demo chain depends on. This is a readiness probe, not a test suite — the
 * behavioral coverage lives in vitest (fake providers). Each section prints
 * PASS / SKIP / FAIL and never logs secrets, env values, or full provider
 * responses.
 *
 * Usage (from apps/api, with .env loaded into the shell):
 *   pnpm run smoke:providers                 # all sections
 *   pnpm run smoke:providers -- storage      # one section
 *   pnpm run smoke:providers -- openai kie   # a subset
 *
 * Sections: storage, openai, kie, render
 *
 * Cost note: `openai` sends one tiny chat completion (a few tokens);
 * `kie` generates exactly ONE image with the default model. Everything else
 * is free/local.
 */

import fs from 'node:fs';
import path from 'node:path';
import { OpenAIAdapter, KieAIAdapter } from '@grafista/model-router';
import { LocalStorageProvider, LOCAL_UPLOAD_DIR } from '../storage/local-provider.js';
import { getRendererAdapter, resolveActiveRendererProviderName } from '../render/adapters/factory.js';

type Outcome = 'PASS' | 'SKIP' | 'FAIL';
const results: Array<{ section: string; outcome: Outcome; detail: string }> = [];

function record(section: string, outcome: Outcome, detail: string): void {
  results.push({ section, outcome, detail });
  console.log(`[smoke] ${section.padEnd(8)} ${outcome.padEnd(5)} ${detail}`);
}

const SMOKE_KEY = 'smoke/step12-storage-roundtrip.txt';

async function smokeStorage(): Promise<void> {
  try {
    const provider = new LocalStorageProvider();
    const body = Buffer.from('grafista step12 storage smoke');
    const ref = await provider.putObject({ key: SMOKE_KEY, body, contentType: 'text/plain' });
    const readBack = await provider.getObjectBuffer({ key: SMOKE_KEY });
    const ok = readBack.equals(body);
    await fs.promises.unlink(path.join(LOCAL_UPLOAD_DIR, SMOKE_KEY)).catch(() => undefined);
    if (!ok) {
      record('storage', 'FAIL', 'local roundtrip read bytes did not match written bytes');
      return;
    }
    record('storage', 'PASS', `local put/get/delete roundtrip ok (bucket=${ref.bucket})`);
  } catch (err) {
    record('storage', 'FAIL', `local storage roundtrip threw: ${(err as Error).message}`);
  }
}

async function smokeOpenAI(): Promise<void> {
  const adapter = new OpenAIAdapter();
  if (!adapter.isAvailable()) {
    record('openai', 'SKIP', 'OPENAI_API_KEY missing');
    return;
  }
  const response = await adapter.complete({
    taskType: 'creative_qa',
    systemPrompt: 'You are a connectivity check. Answer with a single word.',
    userPrompt: 'Reply with exactly: OK',
    outputFormat: 'text',
    maxTokens: 8,
    temperature: 0,
  });
  if (!response.success) {
    record('openai', 'FAIL', `provider error: ${response.error ?? 'unknown'}`);
    return;
  }
  record(
    'openai',
    'PASS',
    `model=${response.model} latencyMs=${response.latencyMs} tokens=${response.usage.totalTokens} contentChars=${response.content.length}`
  );
}

async function smokeKie(): Promise<void> {
  const adapter = new KieAIAdapter();
  if (!adapter.isAvailable()) {
    record('kie', 'SKIP', 'KIE_AI_API_KEY and/or KIE_AI_BASE_URL missing');
    return;
  }
  const response = await adapter.complete({
    taskType: 'image_generation',
    systemPrompt: '',
    userPrompt: 'A plain solid light blue square, flat color, no details. Connectivity test image.',
    outputFormat: 'json',
    metadata: { aspectRatio: '1:1' },
  });
  if (!response.success) {
    record('kie', 'FAIL', `provider error: ${response.error ?? 'unknown'}`);
    return;
  }

  // Success content contract: { images: [{ imageUrl, mimeType? }] } — same
  // payload the visual-generation service validates before touching storage.
  let imageUrl: string | undefined;
  try {
    const parsed = JSON.parse(response.content) as { images?: Array<{ imageUrl?: string }> };
    imageUrl = parsed.images?.[0]?.imageUrl;
  } catch {
    record('kie', 'FAIL', 'success response content was not valid JSON');
    return;
  }
  if (!imageUrl) {
    record('kie', 'FAIL', 'success response had no images[0].imageUrl');
    return;
  }

  // Pull the generated bytes and push them through the real storage provider —
  // the same store-after-generate step the demo chain performs.
  const download = await fetch(imageUrl);
  if (!download.ok) {
    record('kie', 'FAIL', `generated image URL not downloadable (HTTP ${download.status})`);
    return;
  }
  const bytes = Buffer.from(await download.arrayBuffer());
  const storage = new LocalStorageProvider();
  const key = 'smoke/step12-kie-image.png';
  await storage.putObject({ key, body: bytes, contentType: 'image/png' });
  const stored = await storage.getObjectBuffer({ key });
  await fs.promises.unlink(path.join(LOCAL_UPLOAD_DIR, key)).catch(() => undefined);
  record(
    'kie',
    'PASS',
    `model=${response.model} latencyMs=${response.latencyMs} imageBytes=${bytes.length} storedBytes=${stored.length}`
  );
}

async function smokeRender(): Promise<void> {
  const providerName = resolveActiveRendererProviderName();
  try {
    const adapter = getRendererAdapter();
    const output = await adapter.render({
      html: '<!doctype html><html><body style="margin:0;width:320px;height:200px;background:#1e90ff"><h1 style="color:#fff;font-family:sans-serif">Smoke</h1></body></html>',
      width: 320,
      height: 200,
      format: 'png',
    });
    if (!output.buffer || output.buffer.length === 0) {
      record('render', 'FAIL', `${providerName} render returned an empty buffer`);
      return;
    }
    record('render', 'PASS', `provider=${providerName} mime=${output.mimeType} bytes=${output.buffer.length}`);
  } catch (err) {
    const message = (err as Error).message;
    const hint = /playwright|chromium|browser/i.test(message)
      ? ' — if Chromium is missing run: npx playwright install chromium'
      : '';
    record('render', 'FAIL', `${providerName} render threw: ${message}${hint}`);
  }
}

const SECTIONS: Record<string, () => Promise<void>> = {
  storage: smokeStorage,
  openai: smokeOpenAI,
  kie: smokeKie,
  render: smokeRender,
};

async function main(): Promise<void> {
  const requested = process.argv.slice(2).filter((arg) => !arg.startsWith('-'));
  const unknown = requested.filter((name) => !SECTIONS[name]);
  if (unknown.length > 0) {
    console.error(`[smoke] unknown section(s): ${unknown.join(', ')} — valid: ${Object.keys(SECTIONS).join(', ')}`);
    process.exit(2);
  }
  const names = requested.length > 0 ? requested : Object.keys(SECTIONS);
  for (const name of names) {
    await SECTIONS[name]();
  }
  const failed = results.filter((r) => r.outcome === 'FAIL');
  console.log(
    `[smoke] done — ${results.filter((r) => r.outcome === 'PASS').length} pass, ` +
      `${results.filter((r) => r.outcome === 'SKIP').length} skip, ${failed.length} fail`
  );
  process.exit(failed.length > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error('[smoke] FATAL', (err as Error).message);
  process.exit(1);
});
